/*  ReplyIQ — Background Service Worker (Manifest V3)
 *  Handles:
 *    1. ExtensionPay subscription management
 *    2. Gemini API calls (proxied from content script)
 *    3. Usage metering (10 free replies / month)
 */

importScripts('lib/ExtPay.js');

const EXTENSION_ID = 'replyiq'; // Replace with your ExtensionPay extension ID
const FREE_MONTHLY_LIMIT = 10;
const GEMINI_MODEL = 'gemini-2.0-flash';

// ── ExtensionPay Setup ─────────────────────────────────────────────
const extpay = ExtPay(EXTENSION_ID);
extpay.startBackground();

// ── Usage Tracking ─────────────────────────────────────────────────

function getCurrentMonthKey() {
  const now = new Date();
  return `usage_${now.getFullYear()}_${now.getMonth()}`;
}

async function getMonthlyUsage() {
  const key = getCurrentMonthKey();
  const data = await chrome.storage.local.get(key);
  return data[key] || 0;
}

async function incrementUsage() {
  const key = getCurrentMonthKey();
  const current = await getMonthlyUsage();
  await chrome.storage.local.set({ [key]: current + 1 });
  return current + 1;
}

async function canUseReply() {
  // Check paid status first
  try {
    const user = await extpay.getUser();
    if (user.paid) return { allowed: true, remaining: Infinity, isPaid: true };
  } catch (e) {
    console.warn('ExtPay check failed, falling back to free tier', e);
  }

  const used = await getMonthlyUsage();
  const remaining = Math.max(0, FREE_MONTHLY_LIMIT - used);
  return { allowed: remaining > 0, remaining, isPaid: false };
}

// ── Gemini API ─────────────────────────────────────────────────────

async function callGemini(apiKey, threadEmails, tone) {
  const toneInstructions = {
    professional: 'Write in a polished, professional tone. Use proper greetings and sign-offs. Be clear and respectful.',
    casual: 'Write in a friendly, conversational tone. Keep it warm and approachable, but still coherent.',
    direct: 'Write in a concise, no-nonsense tone. Get straight to the point. Minimal pleasantries.'
  };

  const threadContext = threadEmails
    .map((e, i) => `--- Email ${i + 1} ---\nFrom: ${e.from}\nDate: ${e.date}\n\n${e.body}`)
    .join('\n\n');

  const prompt = `You are ReplyIQ, an expert email reply assistant. Based on the email thread below, generate a thoughtful reply to the most recent email.

TONE: ${toneInstructions[tone] || toneInstructions.professional}

RULES:
- Reply ONLY to the last email in the thread, using earlier emails for context.
- Do NOT include a subject line.
- Do NOT wrap the reply in quotes or markdown.
- Match the language of the thread (if the emails are in Italian, reply in Italian, etc.).
- Keep the reply concise but complete.
- If the email asks questions, answer them.
- Sign off naturally but do NOT invent a name — use "[Your Name]" as placeholder.

EMAIL THREAD:
${threadContext}

YOUR REPLY:`;

  const url = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${apiKey}`;

  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: {
        temperature: 0.7,
        maxOutputTokens: 1024
      }
    })
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err?.error?.message || `Gemini API error: ${res.status}`);
  }

  const data = await res.json();
  const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) throw new Error('No response generated by Gemini.');
  return text.trim();
}

// ── Message Handler ────────────────────────────────────────────────

chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
  if (msg.type === 'CHECK_USAGE') {
    canUseReply().then(sendResponse);
    return true; // async
  }

  if (msg.type === 'GENERATE_REPLY') {
    (async () => {
      try {
        // Check usage
        const usage = await canUseReply();
        if (!usage.allowed) {
          sendResponse({
            error: 'limit_reached',
            message: "You've used all 10 free replies this month. Upgrade to ReplyIQ Pro for unlimited replies."
          });
          return;
        }

        // Get API key
        const { gemini_api_key } = await chrome.storage.sync.get('gemini_api_key');
        if (!gemini_api_key) {
          sendResponse({
            error: 'no_api_key',
            message: 'Please set your Gemini API key in the ReplyIQ popup.'
          });
          return;
        }

        // Call Gemini
        const reply = await callGemini(gemini_api_key, msg.threadEmails, msg.tone);

        // Increment usage only on success (skip for paid users)
        if (!usage.isPaid) {
          await incrementUsage();
        }

        const updatedUsage = await canUseReply();
        sendResponse({ reply, remaining: updatedUsage.remaining, isPaid: updatedUsage.isPaid });
      } catch (e) {
        sendResponse({ error: 'api_error', message: e.message });
      }
    })();
    return true; // async
  }

  if (msg.type === 'OPEN_PAYMENT') {
    extpay.openPaymentPage();
    sendResponse({ ok: true });
    return false;
  }

  if (msg.type === 'GET_PAID_STATUS') {
    extpay.getUser().then(user => {
      sendResponse({ paid: user.paid, email: user.email });
    }).catch(() => sendResponse({ paid: false }));
    return true;
  }
});
